### PR TITLE
Add support for Python 3.7+

### LINKED ISSUE #6: Feature request: supporting older Python versions
Thank you for sharing this library! Would it be costly to support Python 3.7+? (Currently declared Python support is for 3.10+.) I think I would be willing to create a PR.

Notes:
* [typing.Protocol](https://docs.python.org/3/library/typing.html?#typing.Protocol) was added in 3.8, to have the support we should use [typing extensions](https://pypi.org/project/typing-extensions/)
* [union operator for types is supported Python 3.10](https://peps.python.org/pep-0604/), so `|` should be converted to `Union`s and `| None` should be converted to `Optional`s for now

### PR DESCRIPTION
**Pull request by m-aciek**
* Uses typing syntax compatible with Python 3.7.
* Adapts the protocols definitions for earlier Python versions.
* Starts to test in CI Python versions from 3.7 to 3.12.
* Extends the test to support partial functionality for Python 3.7.
I wasn't able to make NaiveDateTime/AwareDateTime work properly for Python 3.7 due to interface incompatibilities. Only Date/DateTime is supported as expected for Python 3.7. Full functionality for Python 3.8+.

Closes #6.

### CODE REVIEW

**Review by roman-affirm — APPROVED** [review]
LGTM

**Comment by m-aciek** [comment]
@glyph would it be possible for you to take some time to review the PR?

**Comment by glyph** [comment]
@m-aciek Sure, I'll have a look.  Per <https://endoflife.date/python>, 3.7 is unsupported, but given that this is a load-bearing piece of infrastructure it seems worthwhile to have a bit of extra long-tail support. Plus, I did say I'd look at your PR :).

I'll do a release, but you should expect 3.7 support to be fairly short-lived.

**Comment by glyph** [comment]
@m-aciek  This is included in a new release here: https://pypi.org/project/datetype/2024.2.8/

**Comment by m-aciek** [comment]
Thank you very much!

**Comment by glyph** [comment]
You're welcome! Thanks for your contribution.

**Pull request merged**
