### PR TITLE
Update LICENSE.txt

### PR DESCRIPTION
**Pull request by Tinche**
Clean up typeshed header from the LICENSE.

Guess you copied it from typeshed huh ;)

### CODE REVIEW

**Comment by glyph** [comment]
It was in fact copied from typeshed! Is there a reason to file the serial number off here? :)

**Comment by glyph** [comment]
(approving the workflow just to get you out of "first-time contributor" status :))

**Comment by Tinche** [comment]
> Is there a reason to file the serial number off here? :)

Do you mean why did I remove the entire header? I looked at a Hynek project, saw it wasn't present, and let my inner minimalist do its thing ;)

**Comment by glyph** [comment]
Given that this is straightforwardly a derivative work of `typeshed`, I think I'm going to leave it as-is. Thank you for the attention to detail regardless :)

**Pull request closed without merging**
